# Generated by Django 2.2 on 2020-12-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grade_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='address',
            new_name='city',
        ),
        migrations.AddField(
            model_name='grade',
            name='home',
            field=models.CharField(default='中国', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='phone',
            field=models.CharField(default=119, max_length=200),
            preserve_default=False,
        ),
    ]
