# Generated by Django 2.2 on 2020-12-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grade_manager', '0002_auto_20201209_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='ph',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
