# Generated by Django 2.2 on 2020-12-09 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grade_manager', '0003_student_ph'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='email',
            new_name='username',
        ),
    ]
